const fs = require("fs");
const path = "D:/Ð¡¹¤¾ß×¬Ç®/fitness-coach-crm/src/app/(coach)/coachees/[id]/page.tsx";
let content = fs.readFileSync(path, "utf8");

// Replace the entire problematic header section with clean structure
const oldHeader = \`<div className="flex items-center gap-4 mb-6">\\n          <button onClick={() => router.back()} className="p-2 hover:bg-gray-200 rounded-lg transition">\\n            <ArrowLeft className="w-5 h-5 text-gray-600" />\\n          \\n          <button onClick={() => router.push(/messages?clientId=\${coacheeId})} className="p-2 hover:bg-blue-50 rounded-lg transition ml-auto" title="Chat with client">\\n            <MessageSquare className="w-5 h-5 text-blue-600" />\\n          </button></button>\\n          \\n          <div className="flex items-center gap-3">\\n            <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-full flex items-center justify-center text-white font-bold text-lg">\\n              {(coachee?.full_name || "?")[0]}\\n            </div><button onClick={() => router.push(/messages?clientId=\${coacheeId)} className='p-2 hover:bg-blue-50 rounded-lg transition' title='Chat with client'>\\n            <MessageSquare className='w-5 h-5 text-blue-600' />\\n          </button>\\n            <div>\\n              <h1 className="text-xl font-bold text-gray-900">{coachee?.full_name || "Unknown client"}</h1>\\n              <p className="text-sm text-gray-500">{coachee?.email || ""}</p>\\n            </div>\\n          </div>\\n        </div>\`;

const newHeader = \`<div className="flex items-center justify-between mb-6">\\n          <div className="flex items-center gap-4">\\n            <button onClick={() => router.back()} className="p-2 hover:bg-gray-200 rounded-lg transition" title="Back">\\n              <ArrowLeft className="w-5 h-5 text-gray-600" />\\n            </button>\\n            <div className="flex items-center gap-3">\\n              <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-full flex items-center justify-center text-white font-bold text-lg">\\n                {(coachee?.full_name || "?")[0]}\\n              </div>\\n              <div>\\n                <h1 className="text-xl font-bold text-gray-900">{coachee?.full_name || "Unknown client"}</h1>\\n                <p className="text-sm text-gray-500">{coachee?.email || ""}</p>\\n              </div>\\n            </div>\\n          </div>\\n          <button onClick={() => router.push(`/messages?clientId=\${coacheeId}`)} className="p-2 hover:bg-blue-50 rounded-lg transition ml-auto" title="Chat with client">\\n            <MessageSquare className="w-5 h-5 text-blue-600" />\\n          </button>\\n        </div>\`;

content = content.replace(oldHeader, newHeader);
fs.writeFileSync(path, content, "utf8");
console.log("Fixed detail page header");
